# Generated by Django 4.2.2 on 2023-09-16 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_products_delete_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
